# Generated by Django 4.1.3 on 2023-01-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firsname',
            new_name='firstname',
        ),
    ]
