# Generated by Django 4.1.3 on 2023-01-13 09:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routers',
            fields=[
                ('serialnumber', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('routername', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('enterprise', models.CharField(max_length=255)),
                ('ipaddress', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('topics', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.routers')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
