# Generated by Django 4.1.3 on 2022-12-29 10:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routers',
            fields=[
                ('SerialNumber', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255)),
                ('RouterName', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Enterprise', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('LogID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('topics', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('RouterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.routers')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('InterfaceID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('IpAddress', models.GenericIPAddressField()),
                ('RouterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.routers')),
            ],
        ),
    ]
