<<<<<<< HEAD
# Generated by Django 4.1.3 on 2023-01-03 14:23
=======
# Generated by Django 4.1.3 on 2023-01-07 08:07
>>>>>>> manoel

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
